version: "2"

services:
  db:
    image: mysql:5.7
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DB}
    ports:
     - "${MYSQL_PORT}:3306"

  wordpress:
    image: wordpress:4.4.2-apache
    container_name: wordpress
    links:
      - db
    ports:
      - "${WP_PORT}:80"
    volumes:
     - wordpress-data:/var/www/html
    environment:
     - WORDPRESS_DB_HOST=db:${MYSQL_PORT}
     - WORDPRESS_DB_PASSWORD=${WP_PASSWORD}

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      links:
        - db
      ports:
        - "${PHPMYADMIN_PORT}:80"

  composer:
    image: composer/composer:1.1
    container_name: composer
    volumes:
     - wordpress-data:/app
    command: install

volumes:
  wordpress-data:
    driver: local-persist
    driver_opts:
      mountpoint: ${PWD}/wordpress